language: node_js
node_js:
  - 8
  - 10
  - 12

cache: yarn

env:
  - CHROME_BIN=google-chrome-stable
    MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn build
